apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: ifisio/ifisio
      context: ../iFisioV3-application
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
