server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
  port: 80
logging:
  level:
    ROOT: INFO
    io.github.jhipster: INFO
    com.wellandsword.ifisio: INFO
management:
  metrics:
    export:
      prometheus:
        enabled: false
spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/ifisio;DB_CLOSE_DELAY=-1
    username: iFisio
    password: null
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: io.github.jhipster.domain.util.FixedPostgreSQL10Dialect
    show-sql: false
  liquibase:
    contexts: prod
  mail:
    host: localhost
    port: 25
    username: null
    password: null
  thymeleaf:
    cache: true
jhipster:
  http:
    cache:
      timeToLiveInDays: 1461
  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 1000
  security:
    authentication:
      jwt:
        base64-secret: MmEyNmU3YTM5MzkwODZkZDY1M2Y4MjQ3Yzc2NjNmY2E2ODE4YWYxYzhmMmM2MDhhYWE2ODgwZTViOTU5NTQ5MDUyYzQ5MmZhMDVhOGNlNGE1YWFjMmRiZGIxNDY5ZTJiOGQ2Zjg5ZWFjOWUzODk4YmE5MmQyYjY1NmYwZGQ4MjI=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail:
    base-url: http://my-server-url-to-change
  metrics:
    logs:
      enabled: false
      report-frequency: 60
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
  audit-events:
    retention-period: 30