apiVersion: v1
kind: Secret
metadata:
  name: ifisio-postgresql
  namespace: default
  labels:
    app: ifisio-postgresql
type: Opaque
data:
  postgresql-password: ODYwMTJjMGY5NmYyYzlhYWY4ZGE4OGY1NzM5ZGUyNTlkM2I2YWFiMzQzMzdlZmE3YmFmMGNhNTllZTFj
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ifisio-postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ifisio-postgresql
  template:
    metadata:
      labels:
        app: ifisio-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:12.1
          env:
            - name: POSTGRES_USER
              value: iFisio
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ifisio-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: ifisio-postgresql
  namespace: default
spec:
  selector:
    app: ifisio-postgresql
  ports:
    - port: 5432
